### ISSUE TITLE
Swagger Config

### ISSUE THREAD

**Issue by vikramshanbogar** [swatik1205/springboot-mongodb#1]
Hi,

No config is required wrt swagger just adding a jar is enough

- remove/comment SpringFoxConfig.java
- remove swagger related all previous jars
- add latest swagger jar: 
```
       <!--		Swagger -->
        <!-- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.5.0</version>
        </dependency>
        <!--		Swagger -->
```

run the application, swagger is accessible at: http://localhost:8080/swagger-ui/index.html

![image](https://github.com/swatik1205/springboot-mongodb/assets/70604290/363e0156-ff39-47b4-9993-287cd47c341f)

**Comment by swatik1205** [comment]
Changes done and issue resolved.
